### ISSUE TITLE
Suggest: fix key event?

### ISSUE THREAD

**Issue by etcix** [Jedsek/music-player#1]
It is suggested to add more fonts, and when I cargo run, I can't switch songs when I press the left and right keys, the running speed is too slow.

**Comment by Jedsek** [comment]
> It is suggested to add more fonts, and when I cargo run, I can't switch songs when I press the left and right key

Yes, the fonts and keymaps could be specified by user in the future.
Only the right key exists intentionally present, due to some problem about some code relative to rodio library. (and I want to refactor them)

> the running speed is too slow.

It's very easy to add this feature :)
